#############################################################################
# Makefile for building: testOpenGL
# Generated by qmake (3.0) (Qt 5.6.0)
# Project:  testOpenGL.pro
# Template: app
# Command: /home/yannis/Qt/5.6/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile testOpenGL.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT5BUILD -DQT_QML_DEBUG
CFLAGS        = -pipe -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++0x -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/home/yannis/Qt/5.6/gcc_64/mkspecs/linux-g++
QMAKE         = /home/yannis/Qt/5.6/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = testOpenGL1.0.0
DISTDIR = /home/yannis/Desktop/testOpenGL/.tmp/testOpenGL1.0.0
LINK          = g++
LFLAGS        = -Wl,-z,origin -Wl,-rpath,\$$ORIGIN
LIBS          = $(SUBLIBS) -lGL -lGLU -lGLEW -lSDL2 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = testOpenGL.pro  main.cpp
QMAKE_TARGET  = testOpenGL
DESTDIR       = 
TARGET        = testOpenGL


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: testOpenGL.pro .qmake.cache /home/yannis/Qt/5.6/gcc_64/mkspecs/linux-g++/qmake.conf /home/yannis/Qt/5.6/gcc_64/mkspecs/features/spec_pre.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/common/unix.conf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/common/linux.conf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/common/sanitize.conf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/common/gcc-base.conf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/common/g++-base.conf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/common/g++-unix.conf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/qconfig.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/qt_functions.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/qt_config.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.cache \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/default_pre.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/resolve_config.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/default_post.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/qml_debug.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/warn_on.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/exceptions.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/yacc.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/lex.prf \
		testOpenGL.pro
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile testOpenGL.pro
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/spec_pre.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/common/unix.conf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/common/linux.conf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/common/sanitize.conf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/common/gcc-base.conf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/common/g++-base.conf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/common/g++-unix.conf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/qconfig.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_script.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/qt_functions.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/qt_config.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/spec_post.prf:
.qmake.cache:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/default_pre.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/resolve_config.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/default_post.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/qml_debug.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/warn_on.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/testcase_targets.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/exceptions.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/yacc.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/lex.prf:
testOpenGL.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile testOpenGL.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

